// <auto-generated />
using HotChocolateIssueReproduction.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotChocolateIssueReproduction.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250424183948_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotChocolateIssueReproduction.Data.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name2 = "San Francisco"
                        },
                        new
                        {
                            Id = 2,
                            Name2 = "New York"
                        },
                        new
                        {
                            Id = 3,
                            Name2 = "London"
                        },
                        new
                        {
                            Id = 4,
                            Name2 = "Berlin"
                        },
                        new
                        {
                            Id = 5,
                            Name2 = "Tokyo"
                        });
                });

            modelBuilder.Entity("HotChocolateIssueReproduction.Data.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Website")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Jane is an expert in GraphQL and .NET technologies.",
                            Name = "Jane Doe",
                            Website = "https://janedoe.dev"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "John has been working with EF Core since its inception.",
                            Name = "John Smith",
                            Website = "https://johnsmith.tech"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Alice specializes in Hot Chocolate GraphQL implementations.",
                            Name = "Alice Johnson",
                            Website = "https://alicecodes.io"
                        });
                });

            modelBuilder.Entity("LocationSpeaker", b =>
                {
                    b.Property<int>("LocationsId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("integer");

                    b.HasKey("LocationsId", "SpeakerId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("LocationSpeaker");

                    b.HasData(
                        new
                        {
                            LocationsId = 1,
                            SpeakerId = 1
                        },
                        new
                        {
                            LocationsId = 2,
                            SpeakerId = 1
                        },
                        new
                        {
                            LocationsId = 2,
                            SpeakerId = 2
                        },
                        new
                        {
                            LocationsId = 3,
                            SpeakerId = 2
                        },
                        new
                        {
                            LocationsId = 4,
                            SpeakerId = 3
                        },
                        new
                        {
                            LocationsId = 5,
                            SpeakerId = 3
                        });
                });

            modelBuilder.Entity("LocationSpeaker", b =>
                {
                    b.HasOne("HotChocolateIssueReproduction.Data.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotChocolateIssueReproduction.Data.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
